// Generated by gencpp from file azure_kinect_ros_driver/SetExposureGainResponse.msg
// DO NOT EDIT!


#ifndef AZURE_KINECT_ROS_DRIVER_MESSAGE_SETEXPOSUREGAINRESPONSE_H
#define AZURE_KINECT_ROS_DRIVER_MESSAGE_SETEXPOSUREGAINRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace azure_kinect_ros_driver
{
template <class ContainerAllocator>
struct SetExposureGainResponse_
{
  typedef SetExposureGainResponse_<ContainerAllocator> Type;

  SetExposureGainResponse_()
    {
    }
  SetExposureGainResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetExposureGainResponse_

typedef ::azure_kinect_ros_driver::SetExposureGainResponse_<std::allocator<void> > SetExposureGainResponse;

typedef boost::shared_ptr< ::azure_kinect_ros_driver::SetExposureGainResponse > SetExposureGainResponsePtr;
typedef boost::shared_ptr< ::azure_kinect_ros_driver::SetExposureGainResponse const> SetExposureGainResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace azure_kinect_ros_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "azure_kinect_ros_driver/SetExposureGainResponse";
  }

  static const char* value(const ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetExposureGainResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::azure_kinect_ros_driver::SetExposureGainResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AZURE_KINECT_ROS_DRIVER_MESSAGE_SETEXPOSUREGAINRESPONSE_H
